name: x_action_cable_pro
version: 1.1.6
description: >-
  x_action_cable_v2 abstraction for easy to use classes for dependency injection.
homepage: https://github.com/martinale14/xActionCable
documentation: https://github.com/martinale14/xActionCable

environment:
  sdk: '>=3.4.3 <4.0.0'

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.15.0
  x_action_cable_v2: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

topics:
  - sockets
  - action
  - cable
  - realtime