name: example
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  injectable: ^2.4.2
  json_annotation: ^4.9.0
  x_action_cable_pro: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  x_action_cable_pro_gen:
    path: ../

dependency_overrides:
  x_action_cable_pro:
    path: ../../xActionCablePro

flutter:
  uses-material-design: true