name: x_action_cable_pro_gen
version: 1.1.0
description: >-
  Generator used to complement the x_action_cable_pro package.
homepage: https://github.com/martinale14/xActionCable
documentation: https://github.com/martinale14/xActionCable

environment:
  sdk: '>=3.4.3 <4.0.0'

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  analyzer: ^6.4.1
  build: ^2.4.1
  built_collection: ^5.1.1
  code_builder: ^4.10.0
  dart_style: ^2.3.6
  flutter:
    sdk: flutter
  logging: ^1.2.0
  source_gen: ^1.5.0
  x_action_cable_pro: ^1.1.0
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  build_verify: ^3.1.0
  test: ^1.25.2

flutter:

topics:
  - sockets
  - action
  - cable
  - realtime