name: x_action_cable_v2
version: 1.0.2
description: >-
  Port for x_action_cable, solving problems to enhance app updates.
homepage: https://github.com/martinale14/xActionCable
documentation: https://github.com/martinale14/xActionCable

environment:
  sdk: '>=2.18.5 <4.0.0'

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  web_socket_channel: ^2.2.0
  logger: ^1.1.0
  collection: ^1.16.0

dev_dependencies:
  test:
  

topics:
  - sockets
  - action
  - cable
  - realtime